(defun elcomp--loadup ()
  (interactive)
  (let ((load-path load-path))
    (push (expand-file-name "~/Emacs/el-compilador/") load-path)
    (load "elcomp.el")
    (load "props.el")
    (load "comp-debug.el")
    (load "back.el")
    (load "dom.el")
    (load "dce.el")
    (load "jump-thread.el")))
