(defconst emacs-source "/home/tromey/Emacs/emacs/src/")

(defconst output-file (expand-file-name "elcomp/c-renames.el"))

(defvar defun-names nil)

(dolist (file (directory-files emacs-source t "\\.c\\'"))
  (message "Scanning %s" file)
  (find-file-read-only file)
  (goto-char (point-min))
  (while (re-search-forward
	  "^DEFUN\\s-*(\"\\([^\"]+\\)\",\\s-*\\([a-zA-Z0-9_]+\\)" nil t)
    (let ((lisp-name (match-string 1))
	  (c-name (match-string 2))
	  (replacement nil))
      (setf replacement (concat "F"
				(replace-regexp-in-string "-" "_" lisp-name)))
      (unless (equal replacement c-name)
	(push (cons (intern lisp-name) c-name) defun-names)))))

(find-file output-file)
(erase-buffer)
(insert ";; Autogenerated by get-defuns.el\n")
(pp `(defvar elcomp--c-renames ',defun-names) (current-buffer))
(insert "(provide 'elcomp/c-renames)\n")
(save-buffer)
